/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bcr.fractionfun;

import java.util.NoSuchElementException;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        try (Scanner scanner = new Scanner(System.in)) {
            while (true) {
                System.out.print("? ");
                String line = null;
                try {
                    line = scanner.nextLine();
                }
                catch (NoSuchElementException e) {
                    break;
                }
                System.out.println("= " + Fraction.computeExpression(line));    
            }
        }
    }
}
